-- ============================================================================
-- MCA Platform - Sandbox Seed Data
-- ============================================================================
-- Run after migrations: psql $DATABASE_URL -f database/seed.sql
-- Or via: npm run seed
--
-- Creates:
--   - 2 Organizations
--   - 5 Users (admin, brokers, compliance)
--   - 50 Contacts
--   - 100 Prospects with UCC filings
--   - 30 Deals across pipeline stages
--   - 60 Deal Documents
--   - 100 Communications
--   - 200 Audit Logs
--   - 50 Consent Records
--   - 20 Portfolio Companies
-- ============================================================================

BEGIN;

-- ============================================================================
-- Helper: Generate deterministic random data
-- ============================================================================

-- Set seed for reproducible data
SELECT setseed(0.42);

-- ============================================================================
-- ORGANIZATIONS (2)
-- ============================================================================

INSERT INTO organizations (id, name, slug, subscription_tier, settings) VALUES
(
    '11111111-1111-1111-1111-111111111111',
    'Demo Broker LLC',
    'demo-broker',
    'professional',
    '{"features": ["crm", "pipeline", "compliance"], "branding": {"primaryColor": "#3B82F6"}}'
),
(
    '22222222-2222-2222-2222-222222222222',
    'Test Funding Corp',
    'test-funding',
    'enterprise',
    '{"features": ["crm", "pipeline", "compliance", "portfolio"], "branding": {"primaryColor": "#059669"}}'
);

-- ============================================================================
-- USERS (5)
-- ============================================================================

-- SANDBOX/DEMO USERS — these rows intentionally have a NULL password_hash and
-- therefore CANNOT log in via password authentication. (The earlier comment
-- about a bcrypt hash for 'sandbox123' was inaccurate; no hash is seeded.)
--
-- To enable password login for a sandbox user, set password_hash to a bcrypt
-- hash generated by the app's own hashing routine, e.g.:
--     UPDATE users SET password_hash = '<bcrypt-hash>' WHERE email = '...';
--
-- AUTH-BYPASS GUARD (app responsibility): the authentication layer MUST treat a
-- NULL/empty password_hash as "no password set" and reject password login for
-- such accounts (never compare against / short-circuit on NULL). Password
-- verification must fail closed when password_hash IS NULL.

INSERT INTO users (id, org_id, email, first_name, last_name, role, is_active, email_verified) VALUES
-- Demo Broker LLC users
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    '11111111-1111-1111-1111-111111111111',
    'admin@demo-broker.com',
    'Alex',
    'Admin',
    'admin',
    true,
    true
),
(
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    '11111111-1111-1111-1111-111111111111',
    'sarah@demo-broker.com',
    'Sarah',
    'Broker',
    'broker',
    true,
    true
),
(
    'cccccccc-cccc-cccc-cccc-cccccccccccc',
    '11111111-1111-1111-1111-111111111111',
    'mike@demo-broker.com',
    'Mike',
    'Manager',
    'manager',
    true,
    true
),
-- Test Funding Corp users
(
    'dddddddd-dddd-dddd-dddd-dddddddddddd',
    '22222222-2222-2222-2222-222222222222',
    'admin@test-funding.com',
    'Dana',
    'Director',
    'admin',
    true,
    true
),
(
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
    '22222222-2222-2222-2222-222222222222',
    'compliance@test-funding.com',
    'Chris',
    'Compliance',
    'manager',
    true,
    true
);

-- ============================================================================
-- LENDERS (5)
-- ============================================================================

INSERT INTO lenders (id, org_id, name, contact_name, contact_email, commission_rate, avg_approval_time_hours, is_active) VALUES
(
    'f1111111-1111-1111-1111-111111111111',
    '11111111-1111-1111-1111-111111111111',
    'First Capital Funding',
    'John Capital',
    'submissions@firstcapital.com',
    0.0300,
    24,
    true
),
(
    'f2222222-2222-2222-2222-222222222222',
    '11111111-1111-1111-1111-111111111111',
    'Rapid Business Lending',
    'Maria Rapid',
    'deals@rapidbiz.com',
    0.0250,
    48,
    true
),
(
    'f3333333-3333-3333-3333-333333333333',
    '11111111-1111-1111-1111-111111111111',
    'Merchant Growth Partners',
    'Tom Growth',
    'partner@merchantgrowth.com',
    0.0350,
    36,
    true
),
(
    'f4444444-4444-4444-4444-444444444444',
    '22222222-2222-2222-2222-222222222222',
    'Enterprise Capital Solutions',
    'Lisa Enterprise',
    'ecs@enterprise.com',
    0.0280,
    72,
    true
),
(
    'f5555555-5555-5555-5555-555555555555',
    '22222222-2222-2222-2222-222222222222',
    'Quick Advance Inc',
    'Bob Quick',
    'advance@quickinc.com',
    0.0320,
    12,
    true
);

-- ============================================================================
-- CONTACTS (50)
-- ============================================================================

INSERT INTO contacts (id, org_id, first_name, last_name, email, phone, mobile, title, role, preferred_contact_method, source, is_active, created_by) VALUES
-- Demo Broker contacts (30)
('c0000001-0000-0000-0000-000000000001', '11111111-1111-1111-1111-111111111111', 'James', 'Rodriguez', 'james@acmerestaurant.com', '555-100-0001', '555-200-0001', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000002-0000-0000-0000-000000000002', '11111111-1111-1111-1111-111111111111', 'Maria', 'Santos', 'maria@buildright.com', '555-100-0002', '555-200-0002', 'CEO', 'ceo', 'email', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000003-0000-0000-0000-000000000003', '11111111-1111-1111-1111-111111111111', 'Robert', 'Chen', 'robert@healthplusmed.com', '555-100-0003', '555-200-0003', 'CFO', 'cfo', 'email', 'referral', true, 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
('c0000004-0000-0000-0000-000000000004', '11111111-1111-1111-1111-111111111111', 'Lisa', 'Thompson', 'lisa@techinnovate.io', '555-100-0004', '555-200-0004', 'Founder', 'owner', 'mobile', 'web_lead', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000005-0000-0000-0000-000000000005', '11111111-1111-1111-1111-111111111111', 'Michael', 'Brown', 'mike@metroretail.com', '555-100-0005', '555-200-0005', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000006-0000-0000-0000-000000000006', '11111111-1111-1111-1111-111111111111', 'Jennifer', 'Davis', 'jennifer@sunnycafe.com', '555-100-0006', '555-200-0006', 'General Manager', 'manager', 'sms', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000007-0000-0000-0000-000000000007', '11111111-1111-1111-1111-111111111111', 'William', 'Garcia', 'william@precisionmfg.com', '555-100-0007', '555-200-0007', 'President', 'owner', 'email', 'ucc_filing', true, 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
('c0000008-0000-0000-0000-000000000008', '11111111-1111-1111-1111-111111111111', 'Sarah', 'Martinez', 'sarah@beautyzone.com', '555-100-0008', '555-200-0008', 'Owner', 'owner', 'phone', 'referral', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000009-0000-0000-0000-000000000009', '11111111-1111-1111-1111-111111111111', 'David', 'Johnson', 'david@proelectrical.com', '555-100-0009', '555-200-0009', 'Owner', 'owner', 'mobile', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000010-0000-0000-0000-000000000010', '11111111-1111-1111-1111-111111111111', 'Amanda', 'Wilson', 'amanda@familydental.com', '555-100-0010', '555-200-0010', 'Office Manager', 'manager', 'email', 'ucc_filing', true, 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
('c0000011-0000-0000-0000-000000000011', '11111111-1111-1111-1111-111111111111', 'Christopher', 'Lee', 'chris@autorepairpro.com', '555-100-0011', '555-200-0011', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000012-0000-0000-0000-000000000012', '11111111-1111-1111-1111-111111111111', 'Emily', 'Anderson', 'emily@fitnessfirst.com', '555-100-0012', '555-200-0012', 'Owner', 'owner', 'email', 'web_lead', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000013-0000-0000-0000-000000000013', '11111111-1111-1111-1111-111111111111', 'Daniel', 'Taylor', 'daniel@plumbingexp.com', '555-100-0013', '555-200-0013', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
('c0000014-0000-0000-0000-000000000014', '11111111-1111-1111-1111-111111111111', 'Jessica', 'Thomas', 'jessica@boutiquestyle.com', '555-100-0014', '555-200-0014', 'Owner', 'owner', 'mobile', 'referral', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000015-0000-0000-0000-000000000015', '11111111-1111-1111-1111-111111111111', 'Matthew', 'Moore', 'matt@landscapedesign.com', '555-100-0015', '555-200-0015', 'Owner', 'owner', 'email', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000016-0000-0000-0000-000000000016', '11111111-1111-1111-1111-111111111111', 'Ashley', 'Jackson', 'ashley@petcarecenter.com', '555-100-0016', '555-200-0016', 'CEO', 'ceo', 'phone', 'ucc_filing', true, 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
('c0000017-0000-0000-0000-000000000017', '11111111-1111-1111-1111-111111111111', 'Andrew', 'White', 'andrew@cleanteam.com', '555-100-0017', '555-200-0017', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000018-0000-0000-0000-000000000018', '11111111-1111-1111-1111-111111111111', 'Nicole', 'Harris', 'nicole@bakerydelights.com', '555-100-0018', '555-200-0018', 'Owner', 'owner', 'mobile', 'web_lead', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000019-0000-0000-0000-000000000019', '11111111-1111-1111-1111-111111111111', 'Kevin', 'Clark', 'kevin@roofingmasters.com', '555-100-0019', '555-200-0019', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
('c0000020-0000-0000-0000-000000000020', '11111111-1111-1111-1111-111111111111', 'Rachel', 'Lewis', 'rachel@yogastudio.com', '555-100-0020', '555-200-0020', 'Owner', 'owner', 'email', 'referral', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000021-0000-0000-0000-000000000021', '11111111-1111-1111-1111-111111111111', 'Steven', 'Robinson', 'steven@hvacpros.com', '555-100-0021', '555-200-0021', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000022-0000-0000-0000-000000000022', '11111111-1111-1111-1111-111111111111', 'Michelle', 'Walker', 'michelle@dayspaspa.com', '555-100-0022', '555-200-0022', 'Owner', 'owner', 'mobile', 'ucc_filing', true, 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
('c0000023-0000-0000-0000-000000000023', '11111111-1111-1111-1111-111111111111', 'Brandon', 'Hall', 'brandon@autobody.com', '555-100-0023', '555-200-0023', 'Owner', 'owner', 'phone', 'web_lead', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000024-0000-0000-0000-000000000024', '11111111-1111-1111-1111-111111111111', 'Stephanie', 'Allen', 'stephanie@tutorcenter.com', '555-100-0024', '555-200-0024', 'Director', 'ceo', 'email', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000025-0000-0000-0000-000000000025', '11111111-1111-1111-1111-111111111111', 'Jason', 'Young', 'jason@movingcompany.com', '555-100-0025', '555-200-0025', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
('c0000026-0000-0000-0000-000000000026', '11111111-1111-1111-1111-111111111111', 'Laura', 'King', 'laura@weddingplanner.com', '555-100-0026', '555-200-0026', 'Owner', 'owner', 'email', 'referral', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000027-0000-0000-0000-000000000027', '11111111-1111-1111-1111-111111111111', 'Timothy', 'Wright', 'tim@securitysystems.com', '555-100-0027', '555-200-0027', 'President', 'owner', 'phone', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000028-0000-0000-0000-000000000028', '11111111-1111-1111-1111-111111111111', 'Heather', 'Lopez', 'heather@printshop.com', '555-100-0028', '555-200-0028', 'Owner', 'owner', 'mobile', 'ucc_filing', true, 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
('c0000029-0000-0000-0000-000000000029', '11111111-1111-1111-1111-111111111111', 'Ryan', 'Hill', 'ryan@carwashexpress.com', '555-100-0029', '555-200-0029', 'Owner', 'owner', 'phone', 'web_lead', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
('c0000030-0000-0000-0000-000000000030', '11111111-1111-1111-1111-111111111111', 'Kimberly', 'Scott', 'kim@floraldesign.com', '555-100-0030', '555-200-0030', 'Owner', 'owner', 'email', 'ucc_filing', true, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),

-- Test Funding contacts (20)
('c0000031-0000-0000-0000-000000000031', '22222222-2222-2222-2222-222222222222', 'Thomas', 'Green', 'thomas@bigboxstore.com', '555-100-0031', '555-200-0031', 'CFO', 'cfo', 'email', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000032-0000-0000-0000-000000000032', '22222222-2222-2222-2222-222222222222', 'Patricia', 'Adams', 'patricia@hotelgroup.com', '555-100-0032', '555-200-0032', 'CEO', 'ceo', 'phone', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000033-0000-0000-0000-000000000033', '22222222-2222-2222-2222-222222222222', 'Joseph', 'Nelson', 'joseph@trucking.com', '555-100-0033', '555-200-0033', 'Owner', 'owner', 'phone', 'referral', true, 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'),
('c0000034-0000-0000-0000-000000000034', '22222222-2222-2222-2222-222222222222', 'Margaret', 'Carter', 'margaret@medicalclinic.com', '555-100-0034', '555-200-0034', 'Administrator', 'manager', 'email', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000035-0000-0000-0000-000000000035', '22222222-2222-2222-2222-222222222222', 'Charles', 'Mitchell', 'charles@fooddistributor.com', '555-100-0035', '555-200-0035', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000036-0000-0000-0000-000000000036', '22222222-2222-2222-2222-222222222222', 'Dorothy', 'Perez', 'dorothy@homeservices.com', '555-100-0036', '555-200-0036', 'Owner', 'owner', 'mobile', 'web_lead', true, 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'),
('c0000037-0000-0000-0000-000000000037', '22222222-2222-2222-2222-222222222222', 'Richard', 'Roberts', 'richard@steelworks.com', '555-100-0037', '555-200-0037', 'President', 'owner', 'phone', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000038-0000-0000-0000-000000000038', '22222222-2222-2222-2222-222222222222', 'Susan', 'Turner', 'susan@retailchain.com', '555-100-0038', '555-200-0038', 'CEO', 'ceo', 'email', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000039-0000-0000-0000-000000000039', '22222222-2222-2222-2222-222222222222', 'Edward', 'Phillips', 'edward@constructionllc.com', '555-100-0039', '555-200-0039', 'Owner', 'owner', 'phone', 'referral', true, 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'),
('c0000040-0000-0000-0000-000000000040', '22222222-2222-2222-2222-222222222222', 'Nancy', 'Campbell', 'nancy@lawfirm.com', '555-100-0040', '555-200-0040', 'Managing Partner', 'owner', 'email', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000041-0000-0000-0000-000000000041', '22222222-2222-2222-2222-222222222222', 'George', 'Parker', 'george@manufacturingco.com', '555-100-0041', '555-200-0041', 'CFO', 'cfo', 'phone', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000042-0000-0000-0000-000000000042', '22222222-2222-2222-2222-222222222222', 'Helen', 'Evans', 'helen@retailgroup.com', '555-100-0042', '555-200-0042', 'Owner', 'owner', 'email', 'web_lead', true, 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'),
('c0000043-0000-0000-0000-000000000043', '22222222-2222-2222-2222-222222222222', 'Kenneth', 'Edwards', 'kenneth@logistics.com', '555-100-0043', '555-200-0043', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000044-0000-0000-0000-000000000044', '22222222-2222-2222-2222-222222222222', 'Betty', 'Collins', 'betty@grocerystore.com', '555-100-0044', '555-200-0044', 'Owner', 'owner', 'mobile', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000045-0000-0000-0000-000000000045', '22222222-2222-2222-2222-222222222222', 'Ronald', 'Stewart', 'ronald@equipmentrental.com', '555-100-0045', '555-200-0045', 'Owner', 'owner', 'phone', 'referral', true, 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'),
('c0000046-0000-0000-0000-000000000046', '22222222-2222-2222-2222-222222222222', 'Sharon', 'Sanchez', 'sharon@healthclinic.com', '555-100-0046', '555-200-0046', 'CEO', 'ceo', 'email', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000047-0000-0000-0000-000000000047', '22222222-2222-2222-2222-222222222222', 'Anthony', 'Morris', 'anthony@fastfood.com', '555-100-0047', '555-200-0047', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000048-0000-0000-0000-000000000048', '22222222-2222-2222-2222-222222222222', 'Donna', 'Rogers', 'donna@pharma.com', '555-100-0048', '555-200-0048', 'CFO', 'cfo', 'email', 'web_lead', true, 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'),
('c0000049-0000-0000-0000-000000000049', '22222222-2222-2222-2222-222222222222', 'Mark', 'Reed', 'mark@warehouseops.com', '555-100-0049', '555-200-0049', 'Owner', 'owner', 'phone', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
('c0000050-0000-0000-0000-000000000050', '22222222-2222-2222-2222-222222222222', 'Carol', 'Cook', 'carol@hospitality.com', '555-100-0050', '555-200-0050', 'CEO', 'ceo', 'email', 'ucc_filing', true, 'dddddddd-dddd-dddd-dddd-dddddddddddd');

-- ============================================================================
-- PROSPECTS (100) - with varied industries and priority scores
-- ============================================================================

-- Helper function to generate prospects
DO $$
DECLARE
    industries TEXT[] := ARRAY['restaurant', 'retail', 'construction', 'healthcare', 'manufacturing', 'services', 'technology'];
    states TEXT[] := ARRAY['CA', 'NY', 'TX', 'FL', 'IL', 'PA', 'OH', 'GA', 'NC', 'MI'];
    statuses TEXT[] := ARRAY['new', 'new', 'new', 'claimed', 'claimed', 'contacted', 'qualified', 'dead'];
    org_ids UUID[] := ARRAY['11111111-1111-1111-1111-111111111111'::UUID, '22222222-2222-2222-2222-222222222222'::UUID];

    i INTEGER;
    p_id UUID;
    p_industry TEXT;
    p_state TEXT;
    p_status TEXT;
    p_score INTEGER;
    p_revenue NUMERIC;
    p_default_date DATE;
    p_org_id UUID;
    company_names TEXT[] := ARRAY[
        'Acme Restaurant Group', 'BuildRight Construction', 'HealthPlus Medical', 'TechInnovate Solutions', 'Metro Retail Stores',
        'Sunny Cafe & Bakery', 'Precision Manufacturing', 'Beauty Zone Salon', 'Pro Electrical Services', 'Family Dental Care',
        'AutoRepair Pro', 'Fitness First Gym', 'Plumbing Experts LLC', 'Boutique Style Fashion', 'Landscape Design Co',
        'Pet Care Center', 'Clean Team Services', 'Bakery Delights', 'Roofing Masters', 'Yoga Studio Zen',
        'HVAC Professionals', 'Day Spa Retreat', 'AutoBody Express', 'Tutor Center Academy', 'Moving Company Pro',
        'Wedding Planner Plus', 'Security Systems Inc', 'Print Shop Express', 'Car Wash Express', 'Floral Design Studio',
        'Big Box Retail Corp', 'Hotel Group International', 'Trucking Solutions LLC', 'Medical Clinic Associates', 'Food Distributor Inc',
        'Home Services Network', 'Steel Works Manufacturing', 'Retail Chain Holdings', 'Construction Partners LLC', 'Law Firm Associates',
        'Manufacturing Solutions', 'Retail Group Ventures', 'Logistics Partners', 'Grocery Store Chain', 'Equipment Rental Plus',
        'Health Clinic Network', 'Fast Food Holdings', 'Pharma Distribution', 'Warehouse Operations', 'Hospitality Group',
        'Downtown Bistro', 'Coastal Construction', 'Urgent Care Plus', 'App Development LLC', 'Fashion Outlet Store',
        'Coffee Corner Cafe', 'Heavy Equipment Mfg', 'Nail Salon Beauty', 'Electric Pro Services', 'Orthodontics Center',
        'Tire Shop Express', 'CrossFit Athletics', 'Drain Cleaning Pro', 'Designer Outlet', 'Garden Center Plus',
        'Veterinary Clinic', 'Maid Brigade', 'Artisan Bakery', 'Gutter Specialists', 'Pilates Studio',
        'Cooling Systems Pro', 'Massage Therapy', 'Collision Center', 'Learning Center', 'Relocation Services',
        'Event Planning Co', 'Alarm Systems Inc', 'Copy Center Plus', 'Detail Shop Auto', 'Flower Arrangement',
        'Mega Mart Retail', 'Resort & Suites', 'Freight Solutions', 'Specialty Clinic', 'Wholesale Foods',
        'Handyman Network', 'Metal Fabrication', 'Apparel Outlets', 'Building Partners', 'Legal Associates',
        'Industrial Supply', 'Discount Stores', 'Transport Services', 'Supermarket Chain', 'Tool Rental Center',
        'Wellness Center', 'QSR Holdings', 'Med Supply Dist', 'Storage Solutions', 'Inn & Suites Group'
    ];
BEGIN
    FOR i IN 1..100 LOOP
        p_id := uuid_generate_v4();
        p_industry := industries[1 + (i % 7)];
        p_state := states[1 + (i % 10)];
        p_status := statuses[1 + (i % 8)];
        p_score := 50 + (random() * 50)::INTEGER;
        p_revenue := (500000 + (random() * 10000000))::NUMERIC(15,2);
        p_default_date := CURRENT_DATE - (30 + (random() * 300)::INTEGER);
        p_org_id := org_ids[1 + (i % 2)];

        INSERT INTO prospects (
            id, org_id, company_name, company_name_normalized, industry, state,
            status, priority_score, default_date, time_since_default,
            estimated_revenue, narrative
        ) VALUES (
            p_id,
            p_org_id,
            company_names[i],
            LOWER(company_names[i]),
            p_industry,
            p_state,
            p_status,
            p_score,
            p_default_date,
            (CURRENT_DATE - p_default_date)::INTEGER,
            p_revenue,
            'Prospect identified from UCC filing analysis. ' ||
            CASE p_industry
                WHEN 'restaurant' THEN 'Restaurant industry showing strong recovery signals.'
                WHEN 'retail' THEN 'Retail business with expansion opportunities.'
                WHEN 'construction' THEN 'Construction company with active projects.'
                WHEN 'healthcare' THEN 'Healthcare provider with stable revenue.'
                WHEN 'manufacturing' THEN 'Manufacturing operations with equipment needs.'
                WHEN 'services' THEN 'Service business with growth potential.'
                ELSE 'Technology company with scaling requirements.'
            END
        );

        -- Create 2-4 UCC filings per prospect
        FOR j IN 1..(2 + (random() * 2)::INTEGER) LOOP
            INSERT INTO ucc_filings (
                external_id, filing_date, debtor_name, debtor_name_normalized,
                secured_party, secured_party_normalized, state, lien_amount,
                status, filing_type, source
            ) VALUES (
                p_state || '-2024-' || LPAD((i * 1000 + j)::TEXT, 6, '0'),
                p_default_date - (j * 30),
                company_names[i],
                LOWER(company_names[i]),
                CASE (j % 4)
                    WHEN 0 THEN 'First Capital MCA'
                    WHEN 1 THEN 'Rapid Funding LLC'
                    WHEN 2 THEN 'Merchant Growth Partners'
                    ELSE 'Quick Capital Inc'
                END,
                LOWER(CASE (j % 4)
                    WHEN 0 THEN 'First Capital MCA'
                    WHEN 1 THEN 'Rapid Funding LLC'
                    WHEN 2 THEN 'Merchant Growth Partners'
                    ELSE 'Quick Capital Inc'
                END),
                p_state,
                (50000 + random() * 200000)::NUMERIC(15,2),
                CASE WHEN j = 1 THEN 'lapsed' ELSE 'terminated' END,
                'UCC-1',
                'state-portal'
            );
        END LOOP;
    END LOOP;
END $$;

-- Link first 50 prospects to contacts (prospect_contacts junction)
INSERT INTO prospect_contacts (prospect_id, contact_id, is_primary, relationship)
SELECT
    p.id,
    c.id,
    true,
    CASE c.role
        WHEN 'owner' THEN 'owner'
        WHEN 'ceo' THEN 'decision_maker'
        WHEN 'cfo' THEN 'decision_maker'
        ELSE 'influencer'
    END
FROM (SELECT id, ROW_NUMBER() OVER () as rn FROM prospects LIMIT 50) p
JOIN (SELECT id, role, ROW_NUMBER() OVER () as rn FROM contacts) c ON p.rn = c.rn;

-- ============================================================================
-- DEALS (30) - across all pipeline stages
-- ============================================================================

-- First, ensure we have deal stages (they're auto-created by trigger, but let's be safe)
INSERT INTO deal_stages (org_id, name, slug, stage_order, is_terminal, terminal_type, color)
SELECT '11111111-1111-1111-1111-111111111111', name, slug, stage_order, is_terminal, terminal_type, color
FROM (VALUES
    ('Lead', 'lead', 1, false, NULL, '#6B7280'),
    ('Contacted', 'contacted', 2, false, NULL, '#3B82F6'),
    ('Pack Submitted', 'pack-submitted', 3, false, NULL, '#8B5CF6'),
    ('Underwriting', 'underwriting', 4, false, NULL, '#F59E0B'),
    ('Approved', 'approved', 5, false, NULL, '#10B981'),
    ('Contract Out', 'contract-out', 6, false, NULL, '#EC4899'),
    ('Funded', 'funded', 7, true, 'won', '#059669'),
    ('Dead', 'dead', 8, true, 'lost', '#EF4444'),
    ('Withdrawn', 'withdrawn', 9, true, 'withdrawn', '#9CA3AF')
) AS v(name, slug, stage_order, is_terminal, terminal_type, color)
ON CONFLICT (org_id, slug) DO NOTHING;

INSERT INTO deal_stages (org_id, name, slug, stage_order, is_terminal, terminal_type, color)
SELECT '22222222-2222-2222-2222-222222222222', name, slug, stage_order, is_terminal, terminal_type, color
FROM (VALUES
    ('Lead', 'lead', 1, false, NULL, '#6B7280'),
    ('Contacted', 'contacted', 2, false, NULL, '#3B82F6'),
    ('Pack Submitted', 'pack-submitted', 3, false, NULL, '#8B5CF6'),
    ('Underwriting', 'underwriting', 4, false, NULL, '#F59E0B'),
    ('Approved', 'approved', 5, false, NULL, '#10B981'),
    ('Contract Out', 'contract-out', 6, false, NULL, '#EC4899'),
    ('Funded', 'funded', 7, true, 'won', '#059669'),
    ('Dead', 'dead', 8, true, 'lost', '#EF4444'),
    ('Withdrawn', 'withdrawn', 9, true, 'withdrawn', '#9CA3AF')
) AS v(name, slug, stage_order, is_terminal, terminal_type, color)
ON CONFLICT (org_id, slug) DO NOTHING;

-- Insert deals across stages
DO $$
DECLARE
    org1_id UUID := '11111111-1111-1111-1111-111111111111';
    org2_id UUID := '22222222-2222-2222-2222-222222222222';
    user1_id UUID := 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
    user2_id UUID := 'dddddddd-dddd-dddd-dddd-dddddddddddd';

    deal_id UUID;
    stage_slug TEXT;
    stages TEXT[] := ARRAY['lead', 'lead', 'contacted', 'contacted', 'pack-submitted', 'pack-submitted',
                           'underwriting', 'underwriting', 'approved', 'approved',
                           'contract-out', 'funded', 'funded', 'funded', 'dead'];
    amounts INTEGER[] := ARRAY[50000, 75000, 100000, 125000, 150000, 200000, 250000, 300000,
                               350000, 400000, 450000, 500000, 600000, 750000, 100000];
    i INTEGER;
    p_id UUID;
    c_id UUID;
    s_id UUID;
    l_id UUID;
BEGIN
    -- Demo Broker deals (20)
    FOR i IN 1..20 LOOP
        deal_id := uuid_generate_v4();
        stage_slug := stages[1 + (i % 15)];

        -- Get a prospect and contact from org1
        SELECT id INTO p_id FROM prospects WHERE org_id = org1_id LIMIT 1 OFFSET (i - 1);
        SELECT id INTO c_id FROM contacts WHERE org_id = org1_id LIMIT 1 OFFSET (i - 1);
        SELECT id INTO s_id FROM deal_stages WHERE org_id = org1_id AND slug = stage_slug;
        SELECT id INTO l_id FROM lenders WHERE org_id = org1_id LIMIT 1 OFFSET (i % 3);

        INSERT INTO deals (
            id, org_id, prospect_id, contact_id, lender_id, stage_id, assigned_to,
            amount_requested, amount_approved, amount_funded,
            term_months, factor_rate, daily_payment, total_payback,
            use_of_funds, priority, probability, expected_close_date
        ) VALUES (
            deal_id,
            org1_id,
            p_id,
            c_id,
            l_id,
            s_id,
            user1_id,
            amounts[1 + (i % 15)] * 1.0,
            CASE WHEN stage_slug IN ('approved', 'contract-out', 'funded') THEN amounts[1 + (i % 15)] * 0.9 ELSE NULL END,
            CASE WHEN stage_slug = 'funded' THEN amounts[1 + (i % 15)] * 0.85 ELSE NULL END,
            CASE WHEN stage_slug IN ('approved', 'contract-out', 'funded') THEN 6 + (i % 12) ELSE NULL END,
            CASE WHEN stage_slug IN ('approved', 'contract-out', 'funded') THEN 1.25 + (random() * 0.25) ELSE NULL END,
            CASE WHEN stage_slug IN ('approved', 'contract-out', 'funded') THEN (amounts[1 + (i % 15)] * 1.35 / 180)::NUMERIC(12,2) ELSE NULL END,
            CASE WHEN stage_slug IN ('approved', 'contract-out', 'funded') THEN (amounts[1 + (i % 15)] * 1.35)::NUMERIC(15,2) ELSE NULL END,
            CASE (i % 5)
                WHEN 0 THEN 'Working Capital'
                WHEN 1 THEN 'Equipment Purchase'
                WHEN 2 THEN 'Inventory'
                WHEN 3 THEN 'Expansion'
                ELSE 'Payroll'
            END,
            CASE (i % 4) WHEN 0 THEN 'high' WHEN 1 THEN 'urgent' ELSE 'normal' END,
            CASE stage_slug
                WHEN 'lead' THEN 10
                WHEN 'contacted' THEN 25
                WHEN 'pack-submitted' THEN 50
                WHEN 'underwriting' THEN 65
                WHEN 'approved' THEN 85
                WHEN 'contract-out' THEN 95
                WHEN 'funded' THEN 100
                WHEN 'dead' THEN 0
                ELSE 50
            END,
            CURRENT_DATE + ((i * 5) || ' days')::INTERVAL
        );

        -- Add 2 documents per deal
        INSERT INTO deal_documents (deal_id, document_type, file_name, file_path, file_size, mime_type, uploaded_by)
        VALUES
            (deal_id, 'application', 'Application_' || i || '.pdf', '/documents/applications/app_' || i || '.pdf', 250000, 'application/pdf', user1_id),
            (deal_id, 'bank_statement', 'BankStatement_' || i || '.pdf', '/documents/bank/bs_' || i || '.pdf', 500000, 'application/pdf', user1_id);
    END LOOP;

    -- Test Funding deals (10)
    FOR i IN 1..10 LOOP
        deal_id := uuid_generate_v4();
        stage_slug := stages[1 + (i % 15)];

        SELECT id INTO p_id FROM prospects WHERE org_id = org2_id LIMIT 1 OFFSET (i - 1);
        SELECT id INTO c_id FROM contacts WHERE org_id = org2_id LIMIT 1 OFFSET (i - 1);
        SELECT id INTO s_id FROM deal_stages WHERE org_id = org2_id AND slug = stage_slug;
        SELECT id INTO l_id FROM lenders WHERE org_id = org2_id LIMIT 1 OFFSET (i % 2);

        INSERT INTO deals (
            id, org_id, prospect_id, contact_id, lender_id, stage_id, assigned_to,
            amount_requested, term_months, use_of_funds, priority, probability, expected_close_date
        ) VALUES (
            deal_id,
            org2_id,
            p_id,
            c_id,
            l_id,
            s_id,
            user2_id,
            amounts[1 + (i % 15)] * 1.5,
            12,
            'Business Expansion',
            'normal',
            50,
            CURRENT_DATE + ((i * 7) || ' days')::INTERVAL
        );

        INSERT INTO deal_documents (deal_id, document_type, file_name, file_path, file_size, mime_type, uploaded_by)
        VALUES (deal_id, 'application', 'Application_TF_' || i || '.pdf', '/documents/applications/app_tf_' || i || '.pdf', 300000, 'application/pdf', user2_id);
    END LOOP;
END $$;

-- ============================================================================
-- COMMUNICATIONS (100)
-- ============================================================================

DO $$
DECLARE
    org1_id UUID := '11111111-1111-1111-1111-111111111111';
    org2_id UUID := '22222222-2222-2222-2222-222222222222';
    user1_id UUID := 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
    user2_id UUID := 'dddddddd-dddd-dddd-dddd-dddddddddddd';

    channels TEXT[] := ARRAY['email', 'email', 'email', 'sms', 'sms', 'call'];
    statuses TEXT[] := ARRAY['sent', 'delivered', 'opened', 'clicked', 'sent', 'answered'];

    i INTEGER;
    c_id UUID;
    p_id UUID;
    d_id UUID;
BEGIN
    FOR i IN 1..100 LOOP
        -- Get contact and related prospect/deal from appropriate org
        IF i <= 60 THEN
            SELECT id INTO c_id FROM contacts WHERE org_id = org1_id LIMIT 1 OFFSET ((i - 1) % 30);
            SELECT prospect_id INTO p_id FROM prospect_contacts WHERE contact_id = c_id LIMIT 1;
            SELECT id INTO d_id FROM deals WHERE contact_id = c_id LIMIT 1;

            INSERT INTO communications (
                org_id, contact_id, prospect_id, deal_id, sent_by,
                channel, direction,
                from_address, to_address, from_phone, to_phone,
                subject, body,
                status, sent_at
            ) VALUES (
                org1_id,
                c_id,
                p_id,
                d_id,
                user1_id,
                channels[1 + (i % 6)],
                'outbound',
                CASE WHEN channels[1 + (i % 6)] = 'email' THEN 'broker@demo-broker.com' ELSE NULL END,
                CASE WHEN channels[1 + (i % 6)] = 'email' THEN 'contact' || i || '@example.com' ELSE NULL END,
                CASE WHEN channels[1 + (i % 6)] IN ('sms', 'call') THEN '+15551000000' ELSE NULL END,
                CASE WHEN channels[1 + (i % 6)] IN ('sms', 'call') THEN '+1555200' || LPAD(i::TEXT, 4, '0') ELSE NULL END,
                CASE WHEN channels[1 + (i % 6)] = 'email' THEN 'Following up on your financing needs' ELSE NULL END,
                CASE channels[1 + (i % 6)]
                    WHEN 'email' THEN 'Hi, I wanted to follow up regarding your business financing options. We have competitive rates available.'
                    WHEN 'sms' THEN 'Hi! This is Sarah from Demo Broker. Do you have 5 min to discuss financing options?'
                    ELSE 'Call regarding financing inquiry'
                END,
                statuses[1 + (i % 6)],
                NOW() - ((100 - i) || ' hours')::INTERVAL
            );
        ELSE
            SELECT id INTO c_id FROM contacts WHERE org_id = org2_id LIMIT 1 OFFSET ((i - 61) % 20);
            SELECT prospect_id INTO p_id FROM prospect_contacts WHERE contact_id = c_id LIMIT 1;
            SELECT id INTO d_id FROM deals WHERE contact_id = c_id LIMIT 1;

            INSERT INTO communications (
                org_id, contact_id, prospect_id, deal_id, sent_by,
                channel, direction, from_address, to_address, subject, body, status, sent_at
            ) VALUES (
                org2_id,
                c_id,
                p_id,
                d_id,
                user2_id,
                'email',
                'outbound',
                'team@test-funding.com',
                'contact' || i || '@company.com',
                'Business Financing Opportunity',
                'Thank you for your interest in our funding solutions. We can offer competitive terms.',
                'delivered',
                NOW() - ((100 - i) || ' hours')::INTERVAL
            );
        END IF;
    END LOOP;
END $$;

-- ============================================================================
-- AUDIT LOGS (200)
-- ============================================================================

-- Temporarily disable the trigger that prevents inserts
-- Note: In production, you wouldn't do this - audit logs should only be created by the system
DO $$
DECLARE
    org1_id UUID := '11111111-1111-1111-1111-111111111111';
    org2_id UUID := '22222222-2222-2222-2222-222222222222';
    user_ids UUID[] := ARRAY[
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'::UUID,
        'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::UUID,
        'cccccccc-cccc-cccc-cccc-cccccccccccc'::UUID,
        'dddddddd-dddd-dddd-dddd-dddddddddddd'::UUID,
        'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'::UUID
    ];
    actions TEXT[] := ARRAY['create', 'update', 'view', 'export', 'create', 'update', 'view', 'view'];
    entity_types TEXT[] := ARRAY['prospect', 'deal', 'contact', 'communication', 'prospect', 'deal'];

    i INTEGER;
    entity_id UUID;
BEGIN
    FOR i IN 1..200 LOOP
        -- Get a random entity ID based on type
        CASE entity_types[1 + (i % 6)]
            WHEN 'prospect' THEN SELECT id INTO entity_id FROM prospects LIMIT 1 OFFSET (i % 50);
            WHEN 'deal' THEN SELECT id INTO entity_id FROM deals LIMIT 1 OFFSET (i % 25);
            WHEN 'contact' THEN SELECT id INTO entity_id FROM contacts LIMIT 1 OFFSET (i % 45);
            ELSE SELECT id INTO entity_id FROM communications LIMIT 1 OFFSET (i % 80);
        END CASE;

        INSERT INTO audit_logs (
            org_id, user_id, action, entity_type, entity_id,
            changes, ip_address, user_agent, request_id, created_at
        ) VALUES (
            CASE WHEN i % 3 = 0 THEN org2_id ELSE org1_id END,
            user_ids[1 + (i % 5)],
            actions[1 + (i % 8)],
            entity_types[1 + (i % 6)],
            entity_id,
            CASE actions[1 + (i % 8)]
                WHEN 'update' THEN '{"status": {"old": "new", "new": "claimed"}}'::JSONB
                ELSE NULL
            END,
            ('192.168.1.' || (1 + (i % 254)))::INET,
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/120.0.0.0',
            'req-' || substr(md5(random()::text), 1, 16),
            NOW() - ((200 - i) * 30 || ' minutes')::INTERVAL
        );
    END LOOP;
END $$;

-- ============================================================================
-- CONSENT RECORDS (50)
-- ============================================================================

DO $$
DECLARE
    org1_id UUID := '11111111-1111-1111-1111-111111111111';
    org2_id UUID := '22222222-2222-2222-2222-222222222222';
    user1_id UUID := 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';

    consent_types TEXT[] := ARRAY['express_written', 'prior_express', 'marketing_sms', 'marketing_email', 'marketing_call'];
    collection_methods TEXT[] := ARRAY['web_form', 'phone_recording', 'signed_document', 'email_opt_in', 'sms_opt_in'];

    i INTEGER;
    c_id UUID;
BEGIN
    FOR i IN 1..50 LOOP
        SELECT id INTO c_id FROM contacts LIMIT 1 OFFSET (i - 1);

        INSERT INTO consent_records (
            org_id, contact_id, consent_type, channel, is_granted,
            consent_text, consent_version, collection_method,
            collection_url, ip_address, granted_at, collected_by
        ) VALUES (
            CASE WHEN i <= 30 THEN org1_id ELSE org2_id END,
            c_id,
            consent_types[1 + (i % 5)],
            CASE consent_types[1 + (i % 5)]
                WHEN 'marketing_sms' THEN 'sms'
                WHEN 'marketing_email' THEN 'email'
                WHEN 'marketing_call' THEN 'call'
                ELSE 'all'
            END,
            true,
            'I agree to receive communications regarding business financing options.',
            '1.0',
            collection_methods[1 + (i % 5)],
            'https://demo-broker.com/apply',
            ('192.168.1.' || (1 + (i % 254)))::INET,
            NOW() - ((50 - i) || ' days')::INTERVAL,
            user1_id
        );
    END LOOP;
END $$;

-- ============================================================================
-- PORTFOLIO COMPANIES (20)
-- ============================================================================

INSERT INTO portfolio_companies (id, company_name, company_name_normalized, funding_date, funding_amount, current_status)
SELECT
    uuid_generate_v4(),
    p.company_name,
    LOWER(p.company_name),
    CURRENT_DATE - (random() * 365)::INTEGER,
    50000 + (random() * 500000)::NUMERIC(15,2),
    CASE (ROW_NUMBER() OVER ())::INTEGER % 4
        WHEN 0 THEN 'performing'
        WHEN 1 THEN 'performing'
        WHEN 2 THEN 'watch'
        WHEN 3 THEN 'at-risk'
    END
FROM prospects p
WHERE p.status = 'qualified'
LIMIT 20;

-- ============================================================================
-- GROWTH SIGNALS (for top prospects)
-- ============================================================================

DO $$
DECLARE
    signal_types TEXT[] := ARRAY['hiring', 'permit', 'contract', 'expansion', 'equipment'];
    sources TEXT[] := ARRAY['indeed', 'city-permits', 'sam.gov', 'news', 'equipment-dealers'];

    p_id UUID;
    i INTEGER := 0;
BEGIN
    FOR p_id IN (SELECT id FROM prospects WHERE priority_score > 75 LIMIT 30) LOOP
        i := i + 1;

        INSERT INTO growth_signals (
            prospect_id, type, description, detected_date, source_url, score, confidence
        ) VALUES (
            p_id,
            signal_types[1 + (i % 5)],
            CASE signal_types[1 + (i % 5)]
                WHEN 'hiring' THEN 'Posted ' || (2 + (i % 5)) || ' new job openings'
                WHEN 'permit' THEN 'Filed new building permit for expansion'
                WHEN 'contract' THEN 'Awarded government contract worth $' || (100000 + i * 10000)
                WHEN 'expansion' THEN 'Announced new location opening'
                ELSE 'Listed equipment for purchase'
            END,
            CURRENT_DATE - (random() * 30)::INTEGER,
            'https://source.example.com/signal/' || i,
            70 + (random() * 30)::INTEGER,
            0.75 + (random() * 0.25)
        );
    END LOOP;
END $$;

-- ============================================================================
-- HEALTH SCORES (for prospects with signals)
-- ============================================================================

INSERT INTO health_scores (
    prospect_id, grade, score, sentiment_trend, review_count, avg_sentiment, violation_count, recorded_date
)
SELECT
    p.id,
    CASE
        WHEN p.priority_score >= 85 THEN 'A'
        WHEN p.priority_score >= 70 THEN 'B'
        WHEN p.priority_score >= 55 THEN 'C'
        WHEN p.priority_score >= 40 THEN 'D'
        ELSE 'F'
    END,
    p.priority_score,
    CASE (ROW_NUMBER() OVER ())::INTEGER % 3
        WHEN 0 THEN 'improving'
        WHEN 1 THEN 'stable'
        ELSE 'declining'
    END,
    10 + (random() * 200)::INTEGER,
    0.5 + (random() * 0.5),
    (random() * 3)::INTEGER,
    CURRENT_DATE - (random() * 7)::INTEGER
FROM prospects p
WHERE p.priority_score > 60;

-- ============================================================================
-- COMPETITORS (from UCC filings)
-- ============================================================================

INSERT INTO competitors (lender_name, lender_name_normalized, filing_count, avg_deal_size, market_share, industries, top_state, monthly_trend)
VALUES
    ('First Capital MCA', 'first capital mca', 1250, 125000, 15.5, ARRAY['restaurant', 'retail', 'services'], 'NY', 2.3),
    ('Rapid Funding LLC', 'rapid funding llc', 980, 95000, 12.1, ARRAY['construction', 'manufacturing'], 'TX', 1.8),
    ('Merchant Growth Partners', 'merchant growth partners', 875, 150000, 10.8, ARRAY['healthcare', 'technology'], 'CA', 3.5),
    ('Quick Capital Inc', 'quick capital inc', 720, 75000, 8.9, ARRAY['retail', 'services'], 'FL', -0.5),
    ('Business Funding Direct', 'business funding direct', 650, 110000, 8.0, ARRAY['restaurant', 'retail'], 'IL', 1.2),
    ('Express Merchant Capital', 'express merchant capital', 580, 85000, 7.2, ARRAY['services', 'technology'], 'PA', 0.8),
    ('Forward Capital Group', 'forward capital group', 520, 175000, 6.4, ARRAY['manufacturing', 'construction'], 'OH', 2.1),
    ('Pinnacle Funding Solutions', 'pinnacle funding solutions', 450, 200000, 5.6, ARRAY['healthcare'], 'GA', 4.2);

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Run these to verify seed data:
-- SELECT 'Organizations' as entity, COUNT(*) as count FROM organizations
-- UNION ALL SELECT 'Users', COUNT(*) FROM users
-- UNION ALL SELECT 'Contacts', COUNT(*) FROM contacts
-- UNION ALL SELECT 'Prospects', COUNT(*) FROM prospects
-- UNION ALL SELECT 'UCC Filings', COUNT(*) FROM ucc_filings
-- UNION ALL SELECT 'Deals', COUNT(*) FROM deals
-- UNION ALL SELECT 'Deal Documents', COUNT(*) FROM deal_documents
-- UNION ALL SELECT 'Communications', COUNT(*) FROM communications
-- UNION ALL SELECT 'Audit Logs', COUNT(*) FROM audit_logs
-- UNION ALL SELECT 'Consent Records', COUNT(*) FROM consent_records
-- UNION ALL SELECT 'Portfolio Companies', COUNT(*) FROM portfolio_companies
-- UNION ALL SELECT 'Growth Signals', COUNT(*) FROM growth_signals
-- UNION ALL SELECT 'Health Scores', COUNT(*) FROM health_scores
-- UNION ALL SELECT 'Competitors', COUNT(*) FROM competitors;
