#!/bin/bash

# Cloud Agent Delegation Script
# Usage: ./delegate-to-cloud.sh [task_type] [target_file] [priority]

set -e

# Configuration
CONFIG_FILE="cloud-agent-config.json"
TARGET_FILE="${2:-Tomb of the Unknowns.md}"
TASK_TYPE="${1:-analysis}"
PRIORITY="${3:-medium}"
TIMESTAMP=$(date -u +"%Y-%m-%d_%H-%M-%SZ")

echo "🚀 Cloud Agent Delegation Starting..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Task Type: $TASK_TYPE"
echo "Target File: $TARGET_FILE"  
echo "Priority: $PRIORITY"
echo "Timestamp: $TIMESTAMP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Validate inputs
if [ ! -f "$TARGET_FILE" ]; then
    echo "❌ Error: Target file '$TARGET_FILE' not found!"
    exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Error: Configuration file '$CONFIG_FILE' not found!"
    exit 1
fi

# Create results directory
RESULTS_DIR="cloud-agent-results"
mkdir -p "$RESULTS_DIR"

# Generate delegation payload
PAYLOAD_FILE="$RESULTS_DIR/delegation-payload-$TIMESTAMP.json"
cat > "$PAYLOAD_FILE" << EOF
{
  "delegation_id": "$(uuidgen 2>/dev/null || echo "delegate-$TIMESTAMP")",
  "timestamp": "$TIMESTAMP",
  "task": {
    "type": "$TASK_TYPE",
    "target_file": "$TARGET_FILE", 
    "priority": "$PRIORITY"
  },
  "content": {
    "file_size": $(wc -c < "$TARGET_FILE"),
    "line_count": $(wc -l < "$TARGET_FILE"),
    "word_count": $(wc -w < "$TARGET_FILE")
  },
  "processing_config": {
    "atomization_enabled": true,
    "visualization_enabled": true,
    "interactive_features": true,
    "glassmorphism_ui": true
  },
  "status": "queued"
}
EOF

echo "📦 Created delegation payload: $PAYLOAD_FILE"

# Trigger GitHub Actions workflow if available
if [ -f ".github/workflows/cloud-agent-delegation.yml" ] && command -v gh &> /dev/null; then
    echo "🔄 Triggering GitHub Actions workflow..."
    gh workflow run cloud-agent-delegation.yml \
        -f task_type="$TASK_TYPE" \
        -f target_file="$TARGET_FILE" \
        -f priority="$PRIORITY" \
        2>/dev/null && echo "✅ Workflow triggered successfully" || echo "⚠️  Workflow trigger failed (manual trigger may be needed)"
fi

# Local processing fallback
echo "🔄 Performing local analysis..."
node -e "
const fs = require('fs');
const content = fs.readFileSync('$TARGET_FILE', 'utf8');

const analysis = {
    delegation_id: JSON.parse(fs.readFileSync('$PAYLOAD_FILE', 'utf8')).delegation_id,
    timestamp: '$TIMESTAMP',
    task_type: '$TASK_TYPE',
    target_file: '$TARGET_FILE',
    priority: '$PRIORITY',
    content_analysis: {
        total_chars: content.length,
        total_words: content.split(/\s+/).length,
        total_lines: content.split('\n').length,
        paragraphs: content.split('\n\n').length,
        sections: (content.match(/^#+/gm) || []).length
    },
    atomization_breakdown: {
        themes: (content.match(/^#[^#]/gm) || []).length,
        paragraphs: content.split('\n\n').filter(p => p.trim()).length,
        sentences: content.split(/[.!?]+/).filter(s => s.trim()).length,
        unique_words: [...new Set(content.toLowerCase().match(/\b\w+\b/g) || [])].length,
        total_letters: content.replace(/[^a-zA-Z]/g, '').length
    },
    processing_recommendations: {
        visualization_complexity: '$PRIORITY' === 'high' ? 'advanced' : 'standard',
        interactive_features: ['toggle-atomization', 'visual-breakdown', 'data-export'],
        ui_style: 'glassmorphism',
        estimated_processing_time: Math.ceil(content.length / 1000) + ' minutes'
    },
    status: 'analyzed'
};

fs.writeFileSync('$RESULTS_DIR/analysis-$TIMESTAMP.json', JSON.stringify(analysis, null, 2));
console.log('📊 Analysis complete - results saved to cloud-agent-results/analysis-$TIMESTAMP.json');
" 2>/dev/null || echo "⚠️  Node.js analysis skipped (Node.js not available)"

# Create summary
SUMMARY_FILE="$RESULTS_DIR/delegation-summary-$TIMESTAMP.md"
cat > "$SUMMARY_FILE" << EOF
# Cloud Agent Delegation Summary

**Delegation ID:** $(cat "$PAYLOAD_FILE" | grep '"delegation_id"' | cut -d'"' -f4)
**Timestamp:** $TIMESTAMP
**Task Type:** $TASK_TYPE
**Target File:** $TARGET_FILE
**Priority:** $PRIORITY

## Processing Status
- [x] Payload created
- [x] Local analysis completed
- [ ] Cloud processing (pending)
- [ ] Visual generation (pending) 
- [ ] Interactive features (pending)

## Next Steps
1. Monitor GitHub Actions workflow (if triggered)
2. Review analysis results in: \`cloud-agent-results/\`
3. Implement visualization components
4. Add interactive atomization features
5. Apply glassmorphism UI design

## Files Generated
- \`$PAYLOAD_FILE\`
- \`$RESULTS_DIR/analysis-$TIMESTAMP.json\` (if Node.js available)
- \`$SUMMARY_FILE\`

---
*Generated by Cloud Agent Delegation Script v1.0*
EOF

echo "📋 Created summary: $SUMMARY_FILE"
echo ""
echo "✅ Cloud agent delegation process complete!"
echo "📁 Check the '$RESULTS_DIR' directory for all generated files"
echo "🔗 Monitor GitHub Actions for workflow progress (if available)"
echo ""
echo "Next steps:"
echo "  1. Review analysis results"  
echo "  2. Monitor cloud processing"
echo "  3. Implement visual components"
echo "  4. Add interactive features"