#!/bin/bash
# Script to push feature branches and create PRs
# Generated by GitHub Copilot for branch consolidation

set -e  # Exit on error

REPO_DIR="/home/runner/work/public-record-data-scrapper/public-record-data-scrapper"
cd "$REPO_DIR"

echo "🚀 Starting PR creation process..."
echo ""

# Verify branches exist
echo "✓ Verifying feature branches..."
git branch | grep -q "feature/portfolio-companies-fetcher" || { echo "❌ Branch feature/portfolio-companies-fetcher not found"; exit 1; }
git branch | grep -q "feature/academic-affiliations" || { echo "❌ Branch feature/academic-affiliations not found"; exit 1; }
git branch | grep -q "feature/academic-institutions" || { echo "❌ Branch feature/academic-institutions not found"; exit 1; }
echo "✓ All 3 feature branches found locally"
echo ""

# Push branches
echo "📤 Pushing branches to origin..."
echo ""

echo "  Pushing feature/portfolio-companies-fetcher..."
git push -u origin feature/portfolio-companies-fetcher

echo "  Pushing feature/academic-affiliations..."
git push -u origin feature/academic-affiliations

echo "  Pushing feature/academic-institutions..."
git push -u origin feature/academic-institutions

echo ""
echo "✅ All branches pushed successfully!"
echo ""

# Create PRs
echo "📝 Creating pull requests..."
echo ""

echo "  Creating PR #1: Portfolio Companies Fetcher..."
gh pr create \
  --base main \
  --head feature/portfolio-companies-fetcher \
  --title "feat: implement portfolio companies fetcher" \
  --body-file /tmp/pr1-body.md

echo "  Creating PR #2: Academic Affiliations..."
gh pr create \
  --base main \
  --head feature/academic-affiliations \
  --title "feat: extract researcher affiliations from paper data" \
  --body-file /tmp/pr2-body.md

echo "  Creating PR #3: Academic Institutions..."
gh pr create \
  --base main \
  --head feature/academic-institutions \
  --title "feat: extract and populate institutions in network analyzer" \
  --body-file /tmp/pr3-body.md

echo ""
echo "✅ All 3 PRs created successfully!"
echo ""
echo "📋 Next steps:"
echo "  1. Review PRs on GitHub"
echo "  2. Wait for CI checks to pass"
echo "  3. Get approvals"
echo "  4. Merge PRs"
echo "  5. Delete old branches:"
echo "     - academic-affiliation-extraction-638925578143232858"
echo "     - academic-institutions-extraction-18020468117599993822"
echo "     - implement-fetch-portfolio-companies-13136014294268381082"
echo ""
echo "🎉 Done!"
